# Generated by Django 2.1.5 on 2021-01-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='blog_text',
        ),
    ]
