# Generated by Django 2.1.5 on 2021-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20210123_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='media/blog_images/%Y/%m/'),
        ),
    ]
