# Generated by Django 2.1.5 on 2021-02-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_auto_20210208_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='p_image',
        ),
    ]
